### ISSUE TITLE
Password doesn't seem to be working

### ISSUE THREAD

**Issue by foureyes44** [GooborgStudios/synglechance#32]
The terminal asks me to input my steam password, but whenever I try it tells me it was invalid and "Result Code 5". I swear I'm inputting the correct code.

**Comment by vinyldarkscratch** [comment]
Hey, while this is less of a SyngleChance issue and more of a SteamCMD issue, I'd be happy to help out!  Error code 5 in SteamCMD means invalid authorization, and since you're claiming that the password is correct, I'm not sure why it's not functioning.  What I would recommend, and what worked for me, is to login using the regular Steam application, logging into your account and choose "Remember password".  This caches your authentication, so that all you need to do is type "login <username>" and forget about re-entering your password.

Another possibility, have you made sure your username is correct?  Note: it's in the top-right corner of the Steam application, and is not the one publicly displayed anywhere!  (Pretty sure you know that, but just in case.  😛)
