### ISSUE TITLE
Game opens and closes again after deleting dummy save file

### ISSUE THREAD

**Issue by markdegica** [GooborgStudios/synglechance#41]
When launching the game after deleting the dummy save file, it will open and then close again almost instantly. I believe this is also an issue present in the Windows version.

Note: It looked like a bubble with an exclamation mark appeared for an instant before the app closed but it was so fast it was hard to tell.

**Comment by vinyldarkscratch** [comment]
To be honest I've actually never seen the dummy save file before, but that might be due to the fact that I've been switching between machines.  Will try to replicate this!

**Comment by KockaAdmiralac** [comment]
And yeah, this is an issue also present in the Windows version and I'm pretty sure it was intentionally like that, probably because OneShot loads the save file, checks if a flag is true, checks whether `save_progress.oneshot` exists and then deletes the save file if it does and closes the game so the save file will be loaded anew when the user restarts the game.

**Comment by vinyldarkscratch** [comment]
After conversing with Eliza and Kocka, we concluded that this is an intentional feature.  Closing this issue now and dismissing it.
