### ISSUE TITLE
Error when building through Conan (Windows/Linux)

### ISSUE THREAD

**Issue by Speak2Erase** [GooborgStudios/synglechance#64]
See #59 

When I attempt to compile the project using Conan, I get the same error mentioned there. 

![image](https://user-images.githubusercontent.com/54482069/82515207-8abefe00-9acc-11ea-9b7f-8f4101302849.png)

I've tried building in on Linux, but I'm encountering multiple compilation issues using a VM (Most likely the emulated hardware isn't supported by Qt) and have given up trying.  I suck at using Linux anyways and Windows is my preferred development platform. (Using both the build script and Conan)

I've made an issue (https://github.com/elizagamedev/mkxp-oneshot/issues/23) and have gotten no response. Seeing as this repository is actually updated, I shall move it here.

By the way, what exactly is the purpose/relationship between the two repositories? This one is more updated but I can't tell which one is actually used.
Also, I am allowed to modify this right?

**Comment by KockaAdmiralac** [comment]
I think this is tracked in #61 already (which is why QMake build instructions were moved above Conan build instructions in this repository). The preferred way of building OneShot on Linux is using the `make-oneshot-linux.sh` script. It assumes you have OneShot files downloaded from Steam and build dependencies installed ([this](https://gist.github.com/KockaAdmiralac/9155baba75f9e684cc5a0e7826d81526) doesn't work anymore, but has required dependencies listed as commands). Can you try giving it a shot?

> By the way, what exactly is the purpose/relationship between the two repositories?

This one is/was used for development of macOS and Linux ports of OneShot, and some changes were later merged into the main one. The main repository is where OneShot developers publish changes to the engine they've made and is primarily used for building on Windows.

**Comment by Speak2Erase** [comment]
>  I think this is tracked in #61 already (which is why QMake build instructions were moved above Conan build instructions in this repository). The preferred way of building OneShot on Linux is using the make-oneshot-linux.sh script. It assumes you have OneShot files downloaded from Steam and build dependencies installed (this doesn't work anymore, but has required dependencies listed as commands). Can you try giving it a shot?

I have tried. I can't get it to build no matter what I try. As far as I can tell, it's an issue with QT and my Linux VM that I can't really fix without completely remaking that specific VM from scratch. I  know I provided a screenshot of a Linux terminal taken from the thread I mentioned, but it's happening on windows, and I don't think it has to do with the Ruby requirement either, since I have Ruby installed on my computer.

> This one is/was used for development of macOS and Linux ports of OneShot, and some changes were later merged into the main one. The main repository is where OneShot developers publish changes to the engine they've made and is primarily used for building on Windows.

Ok, that explains what this is. (Guess I may as well report some of the macOS issues my friend has been having.) This thread is better off in the main repo, but I don't think the devs have checked the issues at all, considering my thread there that brings up this problem has been left unanswered since last October.

**Comment by KockaAdmiralac** [comment]
Sorry for my late response. Eliza updated the Conan build in the main repository recently (due to the Linux build of OneShot being released on itch.io) and the Conan build instructions there should be working now (though I won't be able to test it for a few days).

**Comment by Speak2Erase** [comment]
Yeah, I noticed. I'm currently in the process of testing it out.
